# Generated by Django 4.1 on 2022-08-10 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='items_available',
            field=models.IntegerField(default=0),
        ),
    ]
